### ISSUE TITLE
Memory leak with multithreadEventLoopGroup never closed with http client

### ISSUE THREAD

**Issue by tchiotludo** [micronaut-projects/micronaut-rxjava2#50]
### Expected Behavior

I use [DefaultHttpClient](https://github.com/kestra-io/plugin-fs/blob/b9a325787ab735e5f42b6bfe92f62018835aab06/src/main/java/io/kestra/plugin/fs/http/AbstractHttp.java#L167) on my application.
I've seen an increase of global thread on my application and especially a lot's of Running Thread with name `multithreadEventLoopGroup-XX-X` that is never stop. 

After digging, I found that the `DefaultHttpClient` is init with : 
https://github.com/micronaut-projects/micronaut-core/blob/29d395f6b74ee7355a146c70aca219d6bfce3704/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java#L472-L479

That lead to this conditions : 
https://github.com/micronaut-projects/micronaut-core/blob/29d395f6b74ee7355a146c70aca219d6bfce3704/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java#L357-L363

Since the `DefaultThreadFactory` is passed, the `shutdownGroup` is `false` and will be never closed. 

I suspect that all http request thread will be never close since we create a new group who no one in order to shutdown this group

### Steps To Reproduce

You can use this test : https://github.com/kestra-io/plugin-fs/blob/b9a325787ab735e5f42b6bfe92f62018835aab06/src/test/java/io/kestra/plugin/fs/http/RequestTest.java#L67.
Launch the test and see that the thread is running even that after the end of the http request. 

### Environment Information

- JDK: 11 

### Version

3.3.4

**Comment by yawkat** [comment]
The issue in your test case is in `RxHttpClient`. That class doesn't delegate the `close` method properly, so the underlying http client is never closed. @graemerocher can I fix this in a minor release in this module? imo it's a bug, but technically someone could rely on the close method being a no-op.

(@tchiotludo for your project you should use the normal micronaut `HttpClient` and move away from `RxHttpClient` since you don't appear to use the reactive API anyway)

**Comment by graemerocher** [comment]
This is a bug an should be fixed in a patch version yes

**Comment by tchiotludo** [comment]
I confirm that using `HttpClient` fixed the issues for non reactive client. 
I also used the [Reactive one](https://github.com/kestra-io/plugin-fs/blob/b9a325787ab735e5f42b6bfe92f62018835aab06/src/main/java/io/kestra/plugin/fs/http/AbstractHttp.java#L170-L174).
Without the fix the leak is present. 
I also try to move to reactor client and the leak is also present on the reactor implementation. 
I think the PR should include the same fix

**Comment by yawkat** [comment]
you're right, i will make a similar pr for reactor and rxjava3.
